### PR TITLE
Update raylib v4 5

### PR DESCRIPTION
**Pull request by gjones007**
This is a pretty big patch set, but I have been using it successfully on Linux.

Covers the recent int to i64 change.  Includes Raygui and Raymath.  Fixes some of the callbacks needed for audio processing.

### CODE REVIEW

**Comment by topcheese** [comment]
I'm wondering how can I test it out on MacOS?  It appeared to me that Irishgreenchitrus had moved on from the project.

**Comment by irishgreencitrus** [comment]
> I'm wondering how can I test it out on MacOS? It appeared to me that Irishgreenchitrus had moved on from the project.

I have not completely moved on from the project, but I have put it on hold over the last few months as life has been very busy. I'm looking to return to the development of this soon, starting with closing these pull requests.

As for MacOS, I do not own a mac so you'd have better luck asking on the V discord in the #gamedev channel, however I assume its similar to Linux.

**Comment by topcheese** [comment]
Thanks for the updates! I'm playing around with converting the raylib examples now.  I'm not a Git guru, so I'm having some trouble trying to figure the best way to manage the changes in my cloned repo.  I'm trying to keep the same format as your original examples.

**Comment by irishgreencitrus** [comment]
The way I run it so that V uses the working tree version of raylib.v rather than the `main` branch is by symlinking it to `~/.vmodules/irishgreencitrus/raylibv`. 

I think on MacOS it is the same as on linux, using `ln -s /home/user/path/to/raylibv /home/user/.vmodules/irishgreencitrus/raylibv`, obviously replacing the former path with the actual path to raylibv and the latter with wherever vmodules is located on MacOS (can be found with `v doctor`)

Let me know if this makes it any easier

**Pull request merged**
